export const data = [
  {name: 'Shao-qi', value: 6},
  {name: 'Shao-li', value: 2},
  {name: 'Shao-ci', value: 3},
  {name: 'Shao-ge', value: 8},
  {name: 'Shao-la', value: 11},
  {name: 'Shao-ki', value: 25},
  {name: 'Shao-qi', value: 12},
  {name: 'Shao-qi', value: 4},
  {name: 'Shao-qi', value: 6},
  {name: 'Shao-qi', value: 14},
  {name: 'Shao-qi', value: 17},
  {name: 'Shao-qi', value: 21},
  {name: 'Shao-qi', value: 25},
  {name: 'Shao-qi', value: 9},
]